### ISSUE TITLE
Support jssbundling

### ISSUE THREAD

**Issue by adrienpoly** [hotwired/spark#12]
I gave it a spin a our app using css_bundling and js_bundling

updating the html works but I am getting this error in the console. 

I suppose it is because I don't have importmaps in my app

![CleanShot 2024-12-18 at 17 52 21@2x](https://github.com/user-attachments/assets/7b203d33-10de-4be7-a593-f999a261bf74)

Given that it seems to work I think it would be best to silence this error

**Comment by jorgemanrubia** [comment]
Yes @adrienpoly. We only support importmaps for now. `jssbundling` on our radar, but we need to see build dedicated support for it.

In any case I'll leave this open as we should handle that more gracefully.

**Comment by TeriyakiBomb** [comment]
I think it'd be good if that was explicit in the readme, it'll save a lot of unnecessary issues being opened 😅
Happy to add if you like

**Comment by jankeesvw** [comment]
This was also my first question :-)

**Comment by jorgemanrubia** [comment]
I think a path here would be to add a new endpoint to return the source given a stimulus controller path. That would let us use a unified reloader that works with both jssbundling and importmaps. It would also simplify not having to parse the import maps or reload the HTML document before that. 

I'll take a stab at this this week.

**Comment by jorgemanrubia** [comment]
I *think* [this change](https://github.com/hotwired/spark/pull/44) will make Hotwire Spark compatible with jsbundling and other alternatives. Tomorrow I'll test and confirm. I'd appreciate it if anyone gives that branch a try to confirm too.

**Comment by TeriyakiBomb** [comment]
I had a go with the default hello controller - adding the controller to a view updates the html as expected. Modifying the textContents string reloads but returns:

![CleanShot 2024-12-24 at 13 45 50@2x](https://github.com/user-attachments/assets/378d8bde-e6f3-4b8d-b836-06059f7e1c6d)

This includes re running the server post install and double checking my gemfile.lock:

`remote: https://github.com/hotwired/spark.git
  revision: e9c255688bd0cdcc581cf0e393ea0597bb2c091c
`

**Comment by jorgemanrubia** [comment]
This is not working to provide hot-reloading for stimulus controllers under jsbundling. Check my reply to @kobaltz [here](https://github.com/hotwired/spark/pull/44#issuecomment-2561629302).

I'll play a bit more with the approach, but I'm afraid a saner way for jsbundling will be to [get this merged](https://github.com/hotwired/spark/pull/40) and use replaces instead of morphing for the jsbundling path.

**Comment by jorgemanrubia** [comment]
Hey @adrienpoly did you try [this branch](https://github.com/hotwired/spark/pull/40) by any chance? That's the only branch that should be triggering a new turbo visit here 🤔

**Comment by jorgemanrubia** [comment]
I went with a different approach here. It will now detect jsbundling and [configure some dedicated options](https://github.com/hotwired/spark/pull/44/files#diff-c609ff6fc8bc66a087d0fc542ba88bfb0c0b69d992687ecc1a5c3f7674e73ae0R30-R35): instead of trying to hot-reload stimulus controllers, it will reload the current page with Turbo (new option introduced by #40).

The problem with hot reloading with jsbundling are dependencies: the browser can't resolve those outside of the bundling environment, so enabling hot-reloading is a much more complex endeavour than when using importmaps.

**Comment by adrienpoly** [comment]
> Hey @adrienpoly did you try [this branch](https://github.com/hotwired/spark/pull/40) by any chance? That's the only branch that should be triggering a new turbo visit here 🤔

I did some more investigating and it is an issue on my side with some legacy esbuild reload that I put in place. Will do some more testing but it is looking good as fare as I could tell

**Comment by jorgemanrubia** [comment]
I'm closing this as jsbundling will work fine now. I'll be happy to consider hot-reloading for stimulus controllers within this path too if something comes with a good idea that isn't terribly complex.

**Comment by adrienpoly** [comment]
> I'm closing this as jsbundling will work fine now. I'll be happy to consider hot-reloading for stimulus controllers within this path too if something comes with a good idea that isn't terribly complex.

I am going to try hotwire-spark with Ruby Vite. The HMR of RubyVite is amazing. I think there is a sweet spot between Spark html morph updates and RubyVite HMR for JS/CSS. This could be an advanced path to get HMR without importmaps

**Comment by SyedMSawaid** [comment]
<img width="1422" alt="Screenshot 2025-01-02 at 2 57 33 AM" src="https://github.com/user-attachments/assets/bbeab490-c85a-408a-8461-a713db351893" />

I am still facing issue with hot-reloading when I change my stimulus controller. Is that not supported yet with js-bundling?

**Comment by jorgemanrubia** [comment]
@SyedMSawaid have you updated to latest? Also, it could be a caching issue (304 response and, thus, not updating the JS library file). Try disabling the cache to see if that fixes it.

**Comment by SyedMSawaid** [comment]
The response seems to be `200` for the js files. I have pulled the latest commit directly from GitHub. 
<img width="906" alt="Screenshot 2025-01-07 at 7 09 29 PM" src="https://github.com/user-attachments/assets/748d5b78-f594-4351-9e73-6072a4e224fc" />

This is how my `Gemfile`, `Gemfile.lock` and `manifest.js` looks like.
<img width="1113" alt="Screenshot 2025-01-07 at 7 12 16 PM" src="https://github.com/user-attachments/assets/6db13824-9996-4101-b86a-74939936eba1" />

**Comment by AzDarGee** [comment]
I am getting this error:

Error on reload_stimulus TypeError: Cannot read properties of null (reading 'text')
    at #parseImportmapJson

Stimulus controllers not reloading (I have esbuild installed instead of importmap)
