### ISSUE TITLE
Option to disable morphing

### ISSUE THREAD

**Issue by KonnorRogers** [hotwired/spark#24]
Libraries like Trix, and a number of other 3rd party javascript libraries tend to have issues with morphing, would it be possible to have an option to disable DOM Diffing and to store scroll position -> hard refresh -> scroll to stored position.

11ty does this with the `domDiff` option https://www.11ty.dev/docs/dev-server/#options and would be a nice way to still use the reloader if you know you have an incompatible page.

**Comment by jorgemanrubia** [comment]
Yes, I like this idea 👍 . Adding this option was something we discussed internally, but we left out for v1. If someone wants to give it a try I'll be happy to review the PR.

To do this, I'd rename the current `HtmlReloader` to `MorphHtmlReloader`, and we could add a new  `HtmlReloader` that does a full reload. The engine could dispacth a command `morph_html_reload` or `html_reload` depending on whether the option is set.

**Comment by jorgemanrubia** [comment]
Or maybe better to keep it a single command and expose the option to the client as we expose the `logging` one. That way the client decides which command to execute.

**Comment by jorgemanrubia** [comment]
Finally I'd go with a Turbo reload here (not a full document reload), to make it smoother. That would introduce a dependency with Turbo, but having Turbo available is a fair assumption here.

**Comment by KonnorRogers** [comment]
Turbo auto binds to the `window` no?

could be a check with a fallback:

```JS
if (window.Turbo) {

} else {

}
```

**Comment by jorgemanrubia** [comment]
Thanks to @codergeek121 for tackling this one 🙏
