### ISSUE TITLE
Support sprockets

### ISSUE THREAD

**Issue by jacob-carlborg-apoex** [hotwired/spark#36]
I have a Rails application that was upgraded from Rails 7 to Rails 8 and uses Sprockets as the asset pipeline. When I just add `hotwire-spark` to the Gemfile I get the following error after bundling and restarting the Rails sever:

```
Asset `hotwire_spark.js` was not declared to be precompiled in production.
Declare links to your assets in `app/assets/config/manifest.js`.
  //= link hotwire_spark.js
and restart your server
```

I followed the instructions and thought everything would be fine. But that won't work in the test or production environment when the gem is only added to the `development` group in the Gemfile.

Is this gem not compatible with Sprockets?

**Comment by jorgemanrubia** [comment]
Yes, only Propshaft now. I'd be happy to add compatibility to sprockets too someone wants to work on the PR. You can see what mission_control-jobs does to support those.

**Comment by jorgemanrubia** [comment]
Released 0.1.9 with this one. Please let us know if still having trouble with sprockets. Thanks @codergeek121.

**Comment by cbmike** [comment]
Maybe we it can work with Rails 7.2 now?

**Comment by jorgemanrubia** [comment]
@cbmike I'd be happy to do that. Would you mind opening a PR relaxing the Rails dependency to >= 7.0.0? Also, it would be good to test it with an actual Rails 7 app.

**Comment by cbmike** [comment]
I've set it to 7.1.3 since I have that app.
https://github.com/hotwired/spark/pull/42
