### ISSUE TITLE
config.asset_host with lambda not working

### ISSUE THREAD

**Issue by optimuspwnius** [hotwired/spark#43]
Using this in your config:

`config.asset_host = -> (asset, request) { "https://cdn.#{ request.domain }" }`

will result in

`ArgumentError: wrong number of arguments (given 1, expected 2)`

I'm guessing spark doesn't have a request object to work with.

**Comment by jorgemanrubia** [comment]
Could you please share the full backtrace and instructions for reproducing this one? I'm a bit confused at first glance.
